# Generated by Django 6.0.3 on 2026-05-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_facility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='x_position',
            field=models.FloatField(blank=True, help_text='SVG-relative X position (0.0–1.0)', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='y_position',
            field=models.FloatField(blank=True, help_text='SVG-relative Y position (0.0–1.0)', null=True),
        ),
    ]
